// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amfpycsmdrswsoarurnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtZnB5Y3NtZHJzd3NvYXJ1cm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTc3NjcsImV4cCI6MjA3MDI5Mzc2N30.d6pNJ1n18_2E4rzPiIAGpv9lRfmSjDAC16CafSvcOc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});